" LaTeX Unicoder.vim
" http://github.com/joom/latex-unicoder.vim

let s:symbols = {
  \  "\\<-"                       : "←",
  \  "\\->"                       : "→",
  \  "\\<="                       : "⇐",
  \  "\\=>"                       : "⇒",
  \  "0"                          : "0",
  \  "1"                          : "1",
  \  "2"                          : "2",
  \  "3"                          : "3",
  \  "4"                          : "4",
  \  "5"                          : "5",
  \  "6"                          : "6",
  \  "7"                          : "7",
  \  "8"                          : "8",
  \  "9"                          : "9",
  \  "!"                          : "!",
  \  "\\#"                        : "#",
  \  "\\$"                        : "$",
  \  "\\%"                        : "%",
  \  "\\&"                        : "&",
  \  "("                          : "(",
  \  ")"                          : ")",
  \  "*"                          : "*",
  \  "+"                          : "+",
  \  ","                          : ",",
  \  "."                          : ".",
  \  "/"                          : "/",
  \  ":"                          : "∶",
  \  ";"                          : ";",
  \  "<"                          : "<",
  \  "="                          : "=",
  \  ">"                          : ">",
  \  "?"                          : "?",
  \  "@"                          : "@",
  \  "A"                          : "𝐴",
  \  "B"                          : "𝐵",
  \  "C"                          : "𝐶",
  \  "D"                          : "𝐷",
  \  "E"                          : "𝐸",
  \  "F"                          : "𝐹",
  \  "G"                          : "𝐺",
  \  "H"                          : "𝐻",
  \  "I"                          : "𝐼",
  \  "J"                          : "𝐽",
  \  "K"                          : "𝐾",
  \  "L"                          : "𝐿",
  \  "M"                          : "𝑀",
  \  "N"                          : "𝑁",
  \  "O"                          : "𝑂",
  \  "P"                          : "𝑃",
  \  "Q"                          : "𝑄",
  \  "R"                          : "𝑅",
  \  "S"                          : "𝑆",
  \  "T"                          : "𝑇",
  \  "U"                          : "𝑈",
  \  "V"                          : "𝑉",
  \  "W"                          : "𝑊",
  \  "X"                          : "𝑋",
  \  "Y"                          : "𝑌",
  \  "Z"                          : "𝑍",
  \  "\\lbrack"                   : "[",
  \  "\\backslash"                : "\\",
  \  "\\rbrack"                   : "]",
  \  "\\_"                        : "_",
  \  "a"                          : "𝑎",
  \  "b"                          : "𝑏",
  \  "c"                          : "𝑐",
  \  "d"                          : "𝑑",
  \  "e"                          : "𝑒",
  \  "f"                          : "𝑓",
  \  "g"                          : "𝑔",
  \  "h"                          : "h",
  \  "i"                          : "𝑖",
  \  "j"                          : "𝑗",
  \  "k"                          : "𝑘",
  \  "l"                          : "𝑙",
  \  "m"                          : "𝑚",
  \  "n"                          : "𝑛",
  \  "o"                          : "𝑜",
  \  "p"                          : "𝑝",
  \  "q"                          : "𝑞",
  \  "r"                          : "𝑟",
  \  "s"                          : "𝑠",
  \  "t"                          : "𝑡",
  \  "u"                          : "𝑢",
  \  "v"                          : "𝑣",
  \  "w"                          : "𝑤",
  \  "x"                          : "𝑥",
  \  "y"                          : "𝑦",
  \  "z"                          : "𝑧",
  \  "\\{"                        : "{",
  \  "|"                          : "|",
  \  "\\}"                        : "}",
  \  "~"                          : "~",
  \  "\\cent"                     : "¢",
  \  "\\pounds"                   : "£",
  \  "\\yen"                      : "¥",
  \  "\\neg"                      : "¬",
  \  "\\pm"                       : "±",
  \  "\\times"                    : "×",
  \  "\\div"                      : "÷",
  \  "\\hat"                      : "x̂",
  \  "\\tilde"                    : "x̃",
  \  "\\bar"                      : "x̄",
  \  "\\overline"                 : "x̅",
  \  "\\breve"                    : "x̆",
  \  "\\dot"                      : "ẋ",
  \  "\\ddot"                     : "ẍ",
  \  "\\utilde"                   : "x̰",
  \  "\\underbar"                 : "x̱",
  \  "\\underline"                : "x̲",
  \  "\\not"                      : "x̸",
  \ '\Alpha'                      : 'Α',
  \ '\Beta'                       : 'Β',
  \ '\Gamma'                      : 'Γ',
  \ '\Delta'                      : 'Δ',
  \ '\Epsilon'                    : 'Ε',
  \ '\Zeta'                       : 'Ζ',
  \ '\Eta'                        : 'Η',
  \ '\Theta'                      : 'Θ',
  \ '\Iota'                       : 'Ι',
  \ '\Kappa'                      : 'Κ',
  \ '\Lambda'                     : 'Λ',
  \ '\Mu'                         : 'Μ',
  \ '\Nu'                         : 'Ν',
  \ '\Xi'                         : 'Ξ',
  \ '\Omicron'                    : 'Ο',
  \ '\Pi'                         : 'Π',
  \ '\Rho'                        : 'Ρ',
  \ '\Sigma'                      : 'Σ',
  \ '\Tau'                        : 'Τ',
  \ '\Upsilon'                    : 'Υ',
  \ '\Phi'                        : 'Φ',
  \ '\Chi'                        : 'Χ',
  \ '\Psi'                        : 'Ψ',
  \ '\Omega'                      : 'Ω',
  \ '\alpha'                      : 'α',
  \ '\beta'                       : 'β',
  \ '\gamma'                      : 'γ',
  \ '\delta'                      : 'δ',
  \ '\epsilon'                    : 'ϵ',
  \ '\zeta'                       : 'ζ',
  \ '\eta'                        : 'η',
  \ '\theta'                      : 'θ',
  \ '\iota'                       : 'ι',
  \ '\kappa'                      : 'κ',
  \ '\lambda'                     : 'λ',
  \ '\mu'                         : 'μ',
  \ '\nu'                         : 'ν',
  \ '\xi'                         : 'ξ',
  \ '\omicron'                    : 'ο',
  \ '\pi'                         : 'π',
  \ '\rho'                        : 'ρ',
  \ '\sigma'                      : 'σ',
  \ '\tau'                        : 'τ',
  \ '\upsilon'                    : 'υ',
  \ '\phi'                        : 'ϕ',
  \ '\chi'                        : 'χ',
  \ '\psi'                        : 'ψ',
  \ '\omega'                      : 'ω',
  \ '\Stigma'                     : 'Ϛ',
  \ '\stigma'                     : 'ϛ',
  \ '\Digamma'                    : 'Ϝ',
  \ '\digamma'                    : 'ϝ',
  \ '\Koppa'                      : 'Ϟ',
  \ '\koppa'                      : 'ϟ',
  \ '\Sampi'                      : 'Ϡ',
  \ '\sampi'                      : 'ϡ',
  \ '\varkappa'                   : 'ϰ',
  \ '\varrho'                     : 'ϱ',
  \ '\varsigma'                   : 'ς',
  \ '\varphi'                     : 'φ',
  \  "\\horizbar"                 : "―",
  \  "\\|"                        : "‖",
  \  "\\dagger"                   : "†",
  \  "\\ddagger"                  : "‡",
  \  "\\vdots"                    : "⋮",
  \  "\\cdots"                    : "⋯",
  \  "\\iddots"                   : "⋰",
  \  "\\ddots"                    : "⋱",
  \  "\\prime"                    : "′",
  \  "\\second"                   : "″",
  \  "\\third"                    : "‴",
  \  "\\backprime"                : "‵",
  \  "\\backdprime"               : "‶",
  \  "\\backtrprime"              : "‷",
  \  "\\Re"                       : "ℜ",
  \  "\\Im"                       : "ℑ",
  \  "\\Euler"                    : "ℇ",
  \  "\\Planckconst"              : "ℎ",
  \  "\\vec"                      : "x⃗",
  \  "\\aleph"                    : "ℵ",
  \  "\\beth"                     : "ℶ",
  \  "\\gimel"                    : "ℷ",
  \  "\\daleth"                   : "ℸ",
  \  "\\hslash"                   : "ℏ",
  \  "\\uparrow"                  : "↑",
  \  "\\downarrow"                : "↓",
  \  "\\leftarrow"                : "←",
  \  "\\rightarrow"               : "→",
  \  "\\nleftarrow"               : "↚",
  \  "\\nrightarrow"              : "↛",
  \  "\\Uparrow"                  : "⇑",
  \  "\\Downarrow"                : "⇓",
  \  "\\Leftarrow"                : "⇐",
  \  "\\Rightarrow"               : "⇒",
  \  "\\leftrightarrow"           : "↔",
  \  "\\nleftrightarrow"          : "↮",
  \  "\\updownarrow"              : "↕",
  \  "\\Leftrightarrow"           : "⇔",
  \  "\\Updownarrow"              : "⇕",
  \  "\\nwarrow"                  : "↖",
  \  "\\nearrow"                  : "↗",
  \  "\\searrow"                  : "↘",
  \  "\\swarrow"                  : "↙",
  \  "\\Nwarrow"                  : "⇖",
  \  "\\Nearrow"                  : "⇗",
  \  "\\Searrow"                  : "⇘",
  \  "\\Swarrow"                  : "⇙",
  \  "\\MapsUp"                   : "↥",
  \  "\\MapsDown"                 : "↧",
  \  "\\mapsfrom"                 : "↤",
  \  "\\mapsto"                   : "↦",
  \  "\\hookleftarrow"            : "↩",
  \  "\\hookrightarrow"           : "↪",
  \  "\\curvearrowleft"           : "↶",
  \  "\\curvearrowright"          : "↷",
  \  "\\circlearrowleft"          : "↺",
  \  "\\circlearrowright"         : "↻",
  \  "\\downuparrows"             : "⇵",
  \  "\\forall"                   : "∀",
  \  "\\exists"                   : "∃",
  \  "\\complement"               : "∁",
  \  "\\partial"                  : "𝜕",
  \  "\\nexists"                  : "∄",
  \  "\\emptyset"                 : "∅",
  \  "\\increment"                : "∆",
  \  "\\nabla"                    : "∇",
  \  "\\in"                       : "∈",
  \  "\\notin"                    : "∉",
  \  "\\QED"                      : "∎",
  \  "\\prod"                     : "∏",
  \  "\\coprod"                   : "∐",
  \  "\\sum"                      : "∑",
  \  "-"                          : "−",
  \  "\\slash"                    : "∕",
  \  "\\smallsetminus"            : "∖",
  \  "\\ast"                      : "∗",
  \  "\\circ"                     : "∘",
  \  "\\bullet"                   : "∙",
  \  "\\sqrt"                     : "√",
  \  "\\sqrt[3]"                  : "∛",
  \  "\\sqrt[4]"                  : "∜",
  \  "\\propto"                   : "∝",
  \  "\\infty"                    : "∞",
  \  "\\rightangle"               : "∟",
  \  "\\angle"                    : "∠",
  \  "\\measuredangle"            : "∡",
  \  "\\sphericalangle"           : "∢",
  \  "\\mid"                      : "∣",
  \  "\\nmid"                     : "∤",
  \  "\\parallel"                 : "∥",
  \  "\\nparallel"                : "∦",
  \  "\\wedge"                    : "∧",
  \  "\\vee"                      : "∨",
  \  "\\land"                     : "∧",
  \  "\\lor"                      : "∨",
  \  "\\cap"                      : "∩",
  \  "\\cup"                      : "∪",
  \  "\\therefore"                : "∴",
  \  "\\because"                  : "∵",
  \  "\\Proportion"               : "∷",
  \  "\\dotminus"                 : "∸",
  \  "\\eqcolon"                  : "≕",
  \  "\\dotsminusdots"            : "∺",
  \  "\\kernelcontraction"        : "∻",
  \  "\\sim"                      : "∼",
  \  "\\backsim"                  : "∽",
  \  "\\invlazys"                 : "∾",
  \  "\\AC"                       : "∿",
  \  "\\wr"                       : "≀",
  \  "\\nsim"                     : "≁",
  \  "\\eqsim"                    : "≂",
  \  "\\simeq"                    : "≃",
  \  "\\nsimeq"                   : "≄",
  \  "\\cong"                     : "≅",
  \  "\\simneqq"                  : "≆",
  \  "\\ncong"                    : "≇",
  \  "\\approx"                   : "≈",
  \  "\\napprox"                  : "≉",
  \  "\\approxeq"                 : "≊",
  \  "\\approxident"              : "≋",
  \  "\\backcong"                 : "≌",
  \  "\\asymp"                    : "≍",
  \  "\\Bumpeq"                   : "≎",
  \  "\\bumpeq"                   : "≏",
  \  "\\doteq"                    : "≐",
  \  "\\Doteq"                    : "≑",
  \  "\\fallingdotseq"            : "≒",
  \  "\\risingdotseq"             : "≓",
  \  "\\coloneq"                  : "≔",
  \  "\\eqcirc"                   : "≖",
  \  "\\circeq"                   : "≗",
  \  "\\arceq"                    : "≘",
  \  "\\corresponds"              : "≙",
  \  "\\veeeq"                    : "≚",
  \  "\\stareq"                   : "≛",
  \  "\\triangleq"                : "≜",
  \  "\\eqdef"                    : "≝",
  \  "\\measeq"                   : "≞",
  \  "\\questeq"                  : "≟",
  \  "\\neq"                      : "≠",
  \  "\\not\\eq"                  : "≠",
  \  "\\equiv"                    : "≡",
  \  "\\nequiv"                   : "≢",
  \  "\\Equiv"                    : "≣",
  \  "\\leq"                      : "≤",
  \  "\\geq"                      : "≥",
  \  "\\leqq"                     : "≦",
  \  "\\geqq"                     : "≧",
  \  "\\lneqq"                    : "≨",
  \  "\\gneqq"                    : "≩",
  \  "\\ll"                       : "≪",
  \  "\\gg"                       : "≫",
  \  "\\between"                  : "≬",
  \  "\\notasymp"                 : "≭",
  \  "\\nless"                    : "≮",
  \  "\\ngtr"                     : "≯",
  \  "\\nleq"                     : "≰",
  \  "\\ngeq"                     : "≱",
  \  "\\lesssim"                  : "≲",
  \  "\\gtrsim"                   : "≳",
  \  "\\NotLessTilde"             : "≴",
  \  "\\NotGreaterTilde"          : "≵",
  \  "\\lessgtr"                  : "≶",
  \  "\\gtrless"                  : "≷",
  \  "\\nlessgtr"                 : "≸",
  \  "\\NotGreaterLess"           : "≹",
  \  "\\prec"                     : "≺",
  \  "\\succ"                     : "≻",
  \  "\\nprec"                    : "⊀",
  \  "\\nsucc"                    : "⊁",
  \  "\\subset"                   : "⊂",
  \  "\\supset"                   : "⊃",
  \  "\\nsubset"                  : "⊄",
  \  "\\nsupset"                  : "⊅",
  \  "\\subseteq"                 : "⊆",
  \  "\\supseteq"                 : "⊇",
  \  "\\nsubseteq"                : "⊈",
  \  "\\nsupseteq"                : "⊉",
  \  "\\subsetneq"                : "⊊",
  \  "\\supsetneq"                : "⊋",
  \  "\\oplus"                    : "⊕",
  \  "\\ominus"                   : "⊖",
  \  "\\otimes"                   : "⊗",
  \  "\\oslash"                   : "⊘",
  \  "\\odot"                     : "⊙",
  \  "\\bigwedge"                 : "⋀",
  \  "\\bigvee"                   : "⋁",
  \  "\\bigcap"                   : "⋂",
  \  "\\bigcup"                   : "⋃",
  \  "\\diamond"                  : "⋄",
  \  "\\cdot"                     : "⋅",
  \  "\\star"                     : "⋆",
  \  "\\divideontimes"            : "⋇",
  \  "\\bowtie"                   : "⋈",
  \  "\\ltimes"                   : "⋉",
  \  "\\rtimes"                   : "⋊",
  \  "\\leftthreetimes"           : "⋋",
  \  "\\rightthreetimes"          : "⋌",
  \  "\\backsimeq"                : "⋍",
  \  "\\curlyvee"                 : "⋎",
  \  "\\curlywedge"               : "⋏",
  \  "\\Subset"                   : "⋐",
  \  "\\Supset"                   : "⋑",
  \  "\\Cap"                      : "⋒",
  \  "\\Cup"                      : "⋓",
  \  "\\pitchfork"                : "⋔",
  \  "\\hash"                     : "⋕",
  \  "\\lessdot"                  : "⋖",
  \  "\\gtrdot"                   : "⋗",
  \  "\\lll"                      : "⋘",
  \  "\\ggg"                      : "⋙",
  \  "\\lesseqgtr"                : "⋚",
  \  "\\gtreqless"                : "⋛",
  \  "\\eqless"                   : "⋜",
  \  "\\eqgtr"                    : "⋝",
  \  "\\curlyeqprec"              : "⋞",
  \  "\\curlyeqsucc"              : "⋟",
  \  "\\npreceq"                  : "⋠",
  \  "\\nsucceq"                  : "⋡",
  \  "\\nsqsubseteq"              : "⋢",
  \  "\\nsqsupseteq"              : "⋣",
  \  "\\sqsubsetneq"              : "⋤",
  \  "\\sqsupsetneq"              : "⋥",
  \  "\\lnsim"                    : "⋦",
  \  "\\gnsim"                    : "⋧",
  \  "\\precnsim"                 : "⋨",
  \  "\\succnsim"                 : "⋩",
  \  "\\ntriangleleft"            : "⋪",
  \  "\\ntriangleright"           : "⋫",
  \  "\\ntrianglelefteq"          : "⋬",
  \  "\\ntrianglerighteq"         : "⋭",
  \  "\\lceil"                    : "⌈",
  \  "\\rceil"                    : "⌉",
  \  "\\lfloor"                   : "⌊",
  \  "\\rfloor"                   : "⌋",
  \  "\\quarternote"              : "♩",
  \  "\\eighthnote"               : "♪",
  \  "\\twonotes"                 : "♫",
  \  "\\sixteenthnote"            : "♬",
  \  "\\flat"                     : "♭",
  \  "\\natural"                  : "♮",
  \  "\\sharp"                    : "♯",
  \  "\\longleftarrow"            : "⟵",
  \  "\\longrightarrow"           : "⟶",
  \  "\\longleftrightarrow"       : "⟷",
  \  "\\Longleftarrow"            : "⟸",
  \  "\\Longrightarrow"           : "⟹",
  \  "\\Longleftrightarrow"       : "⟺",
  \  "\\longmapsfrom"             : "⟻",
  \  "\\longmapsto"               : "⟼",
  \  "\\Longmapsfrom"             : "⟽",
  \  "\\Longmapsto"               : "⟾",
  \  "\\Mapsfrom"                 : "⤆",
  \  "\\Mapsto"                   : "⤇",
  \  "\\leadsto"                  : "⤳",
  \  "\\bigodot"                  : "⨀",
  \  "\\bigoplus"                 : "⨁",
  \  "\\bigotimes"                : "⨂",
  \  "\\bigsqcap"                 : "⨅",
  \  "\\bigsqcup"                 : "⨆",
  \  "\\int"                      : "∫",
  \  "\\iint"                     : "∬",
  \  "\\iiint"                    : "∭",
  \  "\\iiiint"                   : "⨌",
  \  "\\oint"                     : "∮",
  \  "\\oiint"                    : "∯",
  \  "\\oiiint"                   : "∰",
  \  "\\subseteqq"                : "⫅",
  \  "\\supseteqq"                : "⫆",
  \  "\\subsim"                   : "⫇",
  \  "\\supsim"                   : "⫈",
  \  "\\subsetapprox"             : "⫉",
  \  "\\supsetapprox"             : "⫊",
  \  "\\subsetneqq"               : "⫋",
  \  "\\supsetneqq"               : "⫌",
  \  "\\revnmid"                  : "⫮",
  \  "\\mathbf{A}"                : "𝐀",
  \  "\\mathbf{B}"                : "𝐁",
  \  "\\mathbf{C}"                : "𝐂",
  \  "\\mathbf{D}"                : "𝐃",
  \  "\\mathbf{E}"                : "𝐄",
  \  "\\mathbf{F}"                : "𝐅",
  \  "\\mathbf{G}"                : "𝐆",
  \  "\\mathbf{H}"                : "𝐇",
  \  "\\mathbf{I}"                : "𝐈",
  \  "\\mathbf{J}"                : "𝐉",
  \  "\\mathbf{K}"                : "𝐊",
  \  "\\mathbf{L}"                : "𝐋",
  \  "\\mathbf{M}"                : "𝐌",
  \  "\\mathbf{N}"                : "𝐍",
  \  "\\mathbf{O}"                : "𝐎",
  \  "\\mathbf{P}"                : "𝐏",
  \  "\\mathbf{Q}"                : "𝐐",
  \  "\\mathbf{R}"                : "𝐑",
  \  "\\mathbf{S}"                : "𝐒",
  \  "\\mathbf{T}"                : "𝐓",
  \  "\\mathbf{U}"                : "𝐔",
  \  "\\mathbf{V}"                : "𝐕",
  \  "\\mathbf{W}"                : "𝐖",
  \  "\\mathbf{X}"                : "𝐗",
  \  "\\mathbf{Y}"                : "𝐘",
  \  "\\mathbf{Z}"                : "𝐙",
  \  "\\mathbf{a}"                : "𝐚",
  \  "\\mathbf{b}"                : "𝐛",
  \  "\\mathbf{c}"                : "𝐜",
  \  "\\mathbf{d}"                : "𝐝",
  \  "\\mathbf{e}"                : "𝐞",
  \  "\\mathbf{f}"                : "𝐟",
  \  "\\mathbf{g}"                : "𝐠",
  \  "\\mathbf{h}"                : "𝐡",
  \  "\\mathbf{i}"                : "𝐢",
  \  "\\mathbf{j}"                : "𝐣",
  \  "\\mathbf{k}"                : "𝐤",
  \  "\\mathbf{l}"                : "𝐥",
  \  "\\mathbf{m}"                : "𝐦",
  \  "\\mathbf{n}"                : "𝐧",
  \  "\\mathbf{o}"                : "𝐨",
  \  "\\mathbf{p}"                : "𝐩",
  \  "\\mathbf{q}"                : "𝐪",
  \  "\\mathbf{r}"                : "𝐫",
  \  "\\mathbf{s}"                : "𝐬",
  \  "\\mathbf{t}"                : "𝐭",
  \  "\\mathbf{u}"                : "𝐮",
  \  "\\mathbf{v}"                : "𝐯",
  \  "\\mathbf{w}"                : "𝐰",
  \  "\\mathbf{x}"                : "𝐱",
  \  "\\mathbf{y}"                : "𝐲",
  \  "\\mathbf{z}"                : "𝐳",
  \  "\\mathcal{A}"               : "𝒜",
  \  "\\mathcal{B}"               : "ℬ",
  \  "\\mathcal{C}"               : "𝒞",
  \  "\\mathcal{D}"               : "𝒟",
  \  "\\mathcal{E}"               : "ℰ",
  \  "\\mathcal{F}"               : "ℱ",
  \  "\\mathcal{G}"               : "𝒢",
  \  "\\mathcal{H}"               : "ℋ",
  \  "\\mathcal{I}"               : "ℐ",
  \  "\\mathcal{J}"               : "𝒥",
  \  "\\mathcal{K}"               : "𝒦",
  \  "\\mathcal{L}"               : "ℒ",
  \  "\\mathcal{M}"               : "ℳ",
  \  "\\mathcal{N}"               : "𝒩",
  \  "\\mathcal{O}"               : "𝒪",
  \  "\\mathcal{P}"               : "𝒫",
  \  "\\mathcal{Q}"               : "𝒬",
  \  "\\mathcal{R}"               : "ℛ",
  \  "\\mathcal{S}"               : "𝒮",
  \  "\\mathcal{T}"               : "𝒯",
  \  "\\mathcal{U}"               : "𝒰",
  \  "\\mathcal{V}"               : "𝒱",
  \  "\\mathcal{W}"               : "𝒲",
  \  "\\mathcal{X}"               : "𝒳",
  \  "\\mathcal{Y}"               : "𝒴",
  \  "\\mathcal{Z}"               : "𝒵",
  \  "\\mathcal{a}"               : "𝒶",
  \  "\\mathcal{b}"               : "𝒷",
  \  "\\mathcal{c}"               : "𝒸",
  \  "\\mathcal{d}"               : "𝒹",
  \  "\\mathcal{e}"               : "ℯ",
  \  "\\mathcal{f}"               : "𝒻",
  \  "\\mathcal{g}"               : "ℊ",
  \  "\\mathcal{h}"               : "𝒽",
  \  "\\mathcal{i}"               : "𝒾",
  \  "\\mathcal{j}"               : "𝒿",
  \  "\\mathcal{k}"               : "𝓀",
  \  "\\mathcal{l}"               : "𝓁",
  \  "\\mathcal{m}"               : "𝓂",
  \  "\\mathcal{n}"               : "𝓃",
  \  "\\mathcal{o}"               : "ℴ",
  \  "\\mathcal{p}"               : "𝓅",
  \  "\\mathcal{q}"               : "𝓆",
  \  "\\mathcal{r}"               : "𝓇",
  \  "\\mathcal{s}"               : "𝓈",
  \  "\\mathcal{t}"               : "𝓉",
  \  "\\mathcal{u}"               : "𝓊",
  \  "\\mathcal{v}"               : "𝓋",
  \  "\\mathcal{w}"               : "𝓌",
  \  "\\mathcal{x}"               : "𝓍",
  \  "\\mathcal{y}"               : "𝓎",
  \  "\\mathcal{z}"               : "𝓏",
  \  "\\mathbb{\\pi}"             : "ℼ",
  \  "\\mathbb{\\gamma}"          : "ℽ",
  \  "\\mathbb{\\Gamma}"          : "ℾ",
  \  "\\mathbb{\\Pi}"             : "ℿ",
  \  "\\mathbb{\\Sigma}"          : "⅀",
  \  "\\mathbb{A}"                : "𝔸",
  \  "\\mathbb{B}"                : "𝔹",
  \  "\\mathbb{C}"                : "ℂ",
  \  "\\mathbb{D}"                : "𝔻",
  \  "\\mathbb{E}"                : "𝔼",
  \  "\\mathbb{F}"                : "𝔽",
  \  "\\mathbb{G}"                : "𝔾",
  \  "\\mathbb{H}"                : "ℍ",
  \  "\\mathbb{I}"                : "𝕀",
  \  "\\mathbb{J}"                : "𝕁",
  \  "\\mathbb{K}"                : "𝕂",
  \  "\\mathbb{L}"                : "𝕃",
  \  "\\mathbb{M}"                : "𝕄",
  \  "\\mathbb{N}"                : "ℕ",
  \  "\\mathbb{O}"                : "𝕆",
  \  "\\mathbb{P}"                : "ℙ",
  \  "\\mathbb{Q}"                : "ℚ",
  \  "\\mathbb{R}"                : "ℝ",
  \  "\\mathbb{S}"                : "𝕊",
  \  "\\mathbb{T}"                : "𝕋",
  \  "\\mathbb{U}"                : "𝕌",
  \  "\\mathbb{V}"                : "𝕍",
  \  "\\mathbb{W}"                : "𝕎",
  \  "\\mathbb{X}"                : "𝕏",
  \  "\\mathbb{Y}"                : "𝕐",
  \  "\\mathbb{Z}"                : "ℤ",
  \  "\\mathbb{a}"                : "𝕒",
  \  "\\mathbb{b}"                : "𝕓",
  \  "\\mathbb{c}"                : "𝕔",
  \  "\\mathbb{d}"                : "𝕕",
  \  "\\mathbb{e}"                : "𝕖",
  \  "\\mathbb{f}"                : "𝕗",
  \  "\\mathbb{g}"                : "𝕘",
  \  "\\mathbb{h}"                : "𝕙",
  \  "\\mathbb{i}"                : "𝕚",
  \  "\\mathbb{j}"                : "𝕛",
  \  "\\mathbb{k}"                : "𝕜",
  \  "\\mathbb{l}"                : "𝕝",
  \  "\\mathbb{m}"                : "𝕞",
  \  "\\mathbb{n}"                : "𝕟",
  \  "\\mathbb{o}"                : "𝕠",
  \  "\\mathbb{p}"                : "𝕡",
  \  "\\mathbb{q}"                : "𝕢",
  \  "\\mathbb{r}"                : "𝕣",
  \  "\\mathbb{s}"                : "𝕤",
  \  "\\mathbb{t}"                : "𝕥",
  \  "\\mathbb{u}"                : "𝕦",
  \  "\\mathbb{v}"                : "𝕧",
  \  "\\mathbb{w}"                : "𝕨",
  \  "\\mathbb{x}"                : "𝕩",
  \  "\\mathbb{y}"                : "𝕪",
  \  "\\mathbb{z}"                : "𝕫",
  \  "\\mathtt{A}"                : "𝙰",
  \  "\\mathtt{B}"                : "𝙱",
  \  "\\mathtt{C}"                : "𝙲",
  \  "\\mathtt{D}"                : "𝙳",
  \  "\\mathtt{E}"                : "𝙴",
  \  "\\mathtt{F}"                : "𝙵",
  \  "\\mathtt{G}"                : "𝙶",
  \  "\\mathtt{H}"                : "𝙷",
  \  "\\mathtt{I}"                : "𝙸",
  \  "\\mathtt{J}"                : "𝙹",
  \  "\\mathtt{K}"                : "𝙺",
  \  "\\mathtt{L}"                : "𝙻",
  \  "\\mathtt{M}"                : "𝙼",
  \  "\\mathtt{N}"                : "𝙽",
  \  "\\mathtt{O}"                : "𝙾",
  \  "\\mathtt{P}"                : "𝙿",
  \  "\\mathtt{Q}"                : "𝚀",
  \  "\\mathtt{R}"                : "𝚁",
  \  "\\mathtt{S}"                : "𝚂",
  \  "\\mathtt{T}"                : "𝚃",
  \  "\\mathtt{U}"                : "𝚄",
  \  "\\mathtt{V}"                : "𝚅",
  \  "\\mathtt{W}"                : "𝚆",
  \  "\\mathtt{X}"                : "𝚇",
  \  "\\mathtt{Y}"                : "𝚈",
  \  "\\mathtt{Z}"                : "𝚉",
  \  "\\mathtt{a}"                : "𝚊",
  \  "\\mathtt{b}"                : "𝚋",
  \  "\\mathtt{c}"                : "𝚌",
  \  "\\mathtt{d}"                : "𝚍",
  \  "\\mathtt{e}"                : "𝚎",
  \  "\\mathtt{f}"                : "𝚏",
  \  "\\mathtt{g}"                : "𝚐",
  \  "\\mathtt{h}"                : "𝚑",
  \  "\\mathtt{i}"                : "𝚒",
  \  "\\mathtt{j}"                : "𝚓",
  \  "\\mathtt{k}"                : "𝚔",
  \  "\\mathtt{l}"                : "𝚕",
  \  "\\mathtt{m}"                : "𝚖",
  \  "\\mathtt{n}"                : "𝚗",
  \  "\\mathtt{o}"                : "𝚘",
  \  "\\mathtt{p}"                : "𝚙",
  \  "\\mathtt{q}"                : "𝚚",
  \  "\\mathtt{r}"                : "𝚛",
  \  "\\mathtt{s}"                : "𝚜",
  \  "\\mathtt{t}"                : "𝚝",
  \  "\\mathtt{u}"                : "𝚞",
  \  "\\mathtt{v}"                : "𝚟",
  \  "\\mathtt{w}"                : "𝚠",
  \  "\\mathtt{x}"                : "𝚡",
  \  "\\mathtt{y}"                : "𝚢",
  \  "\\mathtt{z}"                : "𝚣",
  \  "\\mathbf{0}"                : "𝟎",
  \  "\\mathbf{1}"                : "𝟏",
  \  "\\mathbf{2}"                : "𝟐",
  \  "\\mathbf{3}"                : "𝟑",
  \  "\\mathbf{4}"                : "𝟒",
  \  "\\mathbf{5}"                : "𝟓",
  \  "\\mathbf{6}"                : "𝟔",
  \  "\\mathbf{7}"                : "𝟕",
  \  "\\mathbf{8}"                : "𝟖",
  \  "\\mathbf{9}"                : "𝟗",
  \  "\\mathbb{0}"                : "𝟘",
  \  "\\mathbb{1}"                : "𝟙",
  \  "\\mathbb{2}"                : "𝟚",
  \  "\\mathbb{3}"                : "𝟛",
  \  "\\mathbb{4}"                : "𝟜",
  \  "\\mathbb{5}"                : "𝟝",
  \  "\\mathbb{6}"                : "𝟞",
  \  "\\mathbb{7}"                : "𝟟",
  \  "\\mathbb{8}"                : "𝟠",
  \  "\\mathbb{9}"                : "𝟡",
  \  "\\mathsf{0}"                : "𝟢",
  \  "\\mathsf{1}"                : "𝟣",
  \  "\\mathsf{2}"                : "𝟤",
  \  "\\mathsf{3}"                : "𝟥",
  \  "\\mathsf{4}"                : "𝟦",
  \  "\\mathsf{5}"                : "𝟧",
  \  "\\mathsf{6}"                : "𝟨",
  \  "\\mathsf{7}"                : "𝟩",
  \  "\\mathsf{8}"                : "𝟪",
  \  "\\mathsf{9}"                : "𝟫",
  \  "\\mathtt{0}"                : "𝟶",
  \  "\\mathtt{1}"                : "𝟷",
  \  "\\mathtt{2}"                : "𝟸",
  \  "\\mathtt{3}"                : "𝟹",
  \  "\\mathtt{4}"                : "𝟺",
  \  "\\mathtt{5}"                : "𝟻",
  \  "\\mathtt{6}"                : "𝟼",
  \  "\\mathtt{7}"                : "𝟽",
  \  "\\mathtt{8}"                : "𝟾",
  \  "\\mathtt{9}"                : "𝟿",
  \  "^0"                         : "⁰",
  \  "^1"                         : "¹",
  \  "^2"                         : "²",
  \  "^3"                         : "³",
  \  "^4"                         : "⁴",
  \  "^5"                         : "⁵",
  \  "^6"                         : "⁶",
  \  "^7"                         : "⁷",
  \  "^8"                         : "⁸",
  \  "^9"                         : "⁹",
  \  "^+"                         : "⁺",
  \  "^-"                         : "⁻",
  \  "^="                         : "⁼",
  \  "^("                         : "⁽",
  \  "^)"                         : "⁾",
  \  "_0"                         : "₀",
  \  "_1"                         : "₁",
  \  "_2"                         : "₂",
  \  "_3"                         : "₃",
  \  "_4"                         : "₄",
  \  "_5"                         : "₅",
  \  "_6"                         : "₆",
  \  "_7"                         : "₇",
  \  "_8"                         : "₈",
  \  "_9"                         : "₉",
  \  "_+"                         : "₊",
  \  "_-"                         : "₋",
  \  "_="                         : "₌",
  \  "_("                         : "₍",
  \  "_)"                         : "₎",
  \  "\frac{1}{2}"                : "½",
  \  "\frac{1}{4}"                : "¼",
  \  "\frac{3}{4}"                : "¾"
  \ }

" Construct a trie from the s:symbols map to allow for efficient searches for
" the longest matching prefix
function! unicoder#build_trie()
  let s:trie = {}

  " For each key-value pair
  for [l:latex, l:sym] in items(s:symbols)
    let l:level = s:trie
    let l:parent = []

    " For each char in the key
    for l:char in split(l:latex, '\zs')
      " Add char to the trie if not already there
      if !has_key(l:level, l:char)
        let l:level[l:char] = ["", {}]
      endif

      " Move down one level
      let l:parent = l:level[l:char]
      let l:level = l:level[l:char][1]
    endfor

    " At the end of the word, put the unicode symbol
    if l:parent != []
      let l:parent[0] = l:sym
    endif
  endfor
endfunction

" Search the trie for the longest matching prefix of the given string
function! unicoder#match_longest(latex)
  let l:level = s:trie

  " If no match default to first character
  let l:len = 1
  let l:val = a:latex[0]
  let l:matched_len = 1

  " For each char
  for l:char in split(a:latex, '\zs')
    " If char is in the trie
    if has_key(l:level, l:char)
      " Set the return value to the stored unicode character if one exists
      if l:level[l:char][0] != ""
        let l:val = l:level[l:char][0]
        let l:matched_len = l:len
      endif

      " Move down a level
      let l:level = l:level[l:char][1]

      let l:len += 1
    else
      " No more matches
      break
    endif
  endfor

  " Return the matching unicode character and how much of the given string was
  " matched
  return [l:val, l:matched_len]
endfunction

function! unicoder#transform_string(code)
  " Build the trie only once
  if !exists('s:trie')
    call unicoder#build_trie()
  endif

  let l:unicode = ""
  let l:code = a:code

  " Continually find matching prefixes until the end of the string
  while l:code != ""
    let [l:match, l:len] = unicoder#match_longest(l:code)

    let l:unicode .= l:match
    let l:code = l:code[l:len:]
  endwhile

  return l:unicode
endfunction

function! unicoder#start(insert)
  let code = input('Enter symbol code (add "\" if required) : ', '', 'customlist,unicoder#start_complete')

  if a:insert > 0
    let isend = col('.') == col('$') - 1
    let how = 'a'
  else
    let how = 'i'
  endif

  let s = unicoder#transform_string(code)
  execute 'normal! ' . how . s

  if a:insert > 0
    if isend
      startinsert!
    else
      startinsert
      normal! l
    endif
  endif
endfunction

function! unicoder#start_complete(a, c, p)
    let s:a = escape(a:a, '\')
    let s:b = "\\\\" . s:a
    return filter(map(keys(s:symbols), "escape(v:val, '\')"),
         \ "v:val =~ '^' . s:a .'.*' || v:val =~ '^' . s:b .'.*'")
endfunction

function! unicoder#selection()
  normal! gv"xy
  let @x = unicoder#transform_string(@x)
  normal! gv"xp
endfunction
